version: '3.8'

services:
  bookstore-db:
    image: mysql:8.0
    container_name: bookstore-db
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=book
      - MYSQL_ROOT_PASSWORD=admin13
    volumes:
      - bookstore_mysql_data:/var/lib/mysql
    networks:
      - bookstore_net

  bookstore-backend:
    build: .
    container_name: bookstore-app
    ports:
      - "1001:1001"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://bookstore-db:3306/book?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=admin13
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQL8Dialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - bookstore-db
    networks:
      - bookstore_net

volumes:
  bookstore_mysql_data:

networks:
  bookstore_net:
    driver: bridge
