pipeline {
    agent any

    stages {
        stage('🔄 Fetch Code') {
            steps {
                echo 'Pulling the latest codebase layout from GitHub...'
            }
        }

        stage('🏗️ Docker Build') {
            steps {
                echo 'Compiling backend code and building production images...'
                sh 'docker-compose build || /usr/bin/docker-compose-alt build'
            }
        }

        stage('🚀 Live Deploy') {
            steps {
                echo 'Safely restarting containerized application services...'
                sh 'docker-compose down || /usr/bin/docker-compose-alt down'
                sh 'docker-compose up -d || /usr/bin/docker-compose-alt up -d'
                echo 'Bookstore system is successfully updated and live on Port 1001!'
            }
        }
    }
}
